# Generated by Django 6.1 on 2026-08-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_en', models.CharField(max_length=100)),
                ('brand_ar', models.CharField(max_length=100)),
                ('model_en', models.CharField(max_length=100)),
                ('model_ar', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('spec', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('oil_visc', models.CharField(max_length=50)),
                ('oil_visc_high_km', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel', models.CharField(max_length=50)),
                ('octane', models.IntegerField()),
                ('spark', models.CharField(max_length=100)),
                ('tire_psi', models.IntegerField()),
                ('oil_capacity', models.CharField(max_length=50)),
                ('recommendations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
