# Generated by Django 6.1 on 2026-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان البنر (للإدارة فقط)', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='رابط الصورة (يفضل استخدام رابط خارجي أو تحميل صورة)', null=True)),
                ('background_color', models.CharField(default='from-blue-700 via-indigo-700 to-purple-700', help_text='لون خلفية التدرج (مثل: from-blue-700 via-indigo-700 to-purple-700)', max_length=50)),
                ('text_color', models.CharField(default='text-white', help_text='لون النص (مثل: text-white, text-black)', max_length=20)),
                ('button_text', models.CharField(default='اعرف المزيد', max_length=50)),
                ('button_url', models.URLField(blank=True, default='#', help_text='الرابط عند الضغط على الزر')),
                ('position', models.CharField(choices=[('hero', 'بنر رئيسي (أعلى الصفحة)'), ('footer', 'بنر سفلي (بين البطاقات والتذييل)'), ('sidebar', 'بنر جانبي (يمين/يسار)'), ('between_cards', 'بنر بين البطاقات')], default='footer', help_text='مكان ظهور البنر', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='ترتيب الظهور (الأرقام الأصغر تظهر أولاً)')),
                ('is_active', models.BooleanField(default=True, help_text='فعّل البنر ليظهر في الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر إعلاني',
                'verbose_name_plural': 'البنرات الإعلانية',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
