# Generated by Django 6.1 on 2026-08-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_adbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='engine_type',
            field=models.CharField(choices=[('regular', 'عادي (Regular)'), ('hybrid', 'هايبرد (Hybrid)'), ('turbo', 'تيربو (Turbo)'), ('diesel', 'ديزل (Diesel)'), ('electric', 'كهربائي (Electric)')], default='regular', max_length=20, verbose_name='نوع المحرك'),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='spec_region',
            field=models.CharField(choices=[('gcc', 'خليجي (GCC)'), ('american', 'أمريكي (American)'), ('european', 'أوروبي (European)'), ('japanese', 'ياباني (Japanese)'), ('other', 'أخرى (Other)')], default='gcc', max_length=20, verbose_name='مواصفات المنطقة'),
        ),
    ]
