# Generated by Django 5.2.17 on 2026-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_sitesettings_hide_result_trim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecification',
            name='battery',
            field=models.TextField(blank=True, help_text='مثال: 55D23L، 60Ah، 12V 70Ah', null=True, verbose_name='البطارية (الحجم/السعة)'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='engine',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='engine_code',
            field=models.TextField(blank=True, help_text='مثال: 2ZR-FE، G4NA، M274', null=True, verbose_name='كود المحرك'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='engine_norm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='fuel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='octane',
            field=models.TextField(help_text='مثال: 91، 95، 91 RON، 91 أو أعلى', verbose_name='الأوكتان'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='oil_brands',
            field=models.TextField(blank=True, help_text='مثال: Mobil 1, Castrol, Total', null=True, verbose_name='ماركات الزيت'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='oil_capacity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='oil_visc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='oil_visc_high_km',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='spark',
            field=models.TextField(blank=True, help_text='مثال: NGK Iridium', null=True, verbose_name='شمعات الاحتراق'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='spec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='tire_size',
            field=models.TextField(default='غير محدد', help_text='مثال: 215/60R16', verbose_name='حجم الإطار'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='transmission_oil_brands',
            field=models.TextField(blank=True, help_text='مثال: Toyota Genuine ATF, Idemitsu, AISIN', null=True, verbose_name='ماركات زيت الناقل'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='transmission_oil_spec',
            field=models.TextField(blank=True, help_text='مثال: ATF WS، ATF SP-III، Dexron VI', null=True, verbose_name='مواصفات زيت الناقل'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='transmission_type',
            field=models.TextField(blank=True, help_text='مثال: أوتوماتيك 6 سرعات، CVT، Manual', null=True, verbose_name='نوع ناقل الحركة'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='trim',
            field=models.TextField(blank=True, help_text='مثال: GLX، EX، سمارت، فل كامل', null=True, verbose_name='الفئة (Trim)'),
        ),
    ]
