# Generated by Django 6.1 on 2026-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carspecification_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='background_color',
            field=models.CharField(default='from-blue-700 via-indigo-700 to-purple-700', max_length=50),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='button_url',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('hero', 'بنر رئيسي (أعلى الصفحة)'), ('footer', 'بنر سفلي (بين البطاقات والتذييل)')], default='footer', max_length=20),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='text_color',
            field=models.CharField(default='text-white', max_length=20),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='engine_type',
            field=models.CharField(choices=[('regular', 'عادي'), ('hybrid', 'هايبرد'), ('turbo', 'تيربو'), ('diesel', 'ديزل'), ('electric', 'كهربائي')], default='regular', max_length=20, verbose_name='نوع المحرك'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='spec_region',
            field=models.CharField(choices=[('gcc', 'خليجي'), ('american', 'أمريكي'), ('european', 'أوروبي'), ('japanese', 'ياباني'), ('other', 'أخرى')], default='gcc', max_length=20, verbose_name='مواصفات المنطقة'),
        ),
    ]
