# Generated by Django 5.2.17 on 2026-09-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_expand_car_specification_text_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='deepseek_api_key',
        ),
    ]
