# Generated by Django 6.1 on 2026-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_adbanner_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='oil_brands',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ماركات الزيت'),
        ),
    ]
