# Generated by Django 6.1 on 2026-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carspecification_oil_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbanner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='اختر صورة للبنر (يفضل 1200x400 بكسل)', null=True, upload_to='banners/', verbose_name='صورة البنر'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='background_color',
            field=models.CharField(default='from-blue-700 via-indigo-700 to-purple-700', help_text='يستخدم هذا اللون إذا لم ترفع صورة', max_length=50, verbose_name='لون الخلفية (في حالة عدم وجود صورة)'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='button_text',
            field=models.CharField(default='اعرف المزيد', max_length=50, verbose_name='نص الزر'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='button_url',
            field=models.URLField(blank=True, default='#', help_text='مثال: /offers/ أو https://example.com', verbose_name='رابط الزر'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='✔️ ظاهر في الموقع | ❌ مخفي', verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='order',
            field=models.IntegerField(default=0, help_text='0 = يظهر أولاً', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('hero', 'بنر رئيسي (أعلى الصفحة)'), ('footer', 'بنر سفلي (بين البطاقات والتذييل)')], default='footer', max_length=20, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='text_color',
            field=models.CharField(default='text-white', help_text='text-white أو text-black', max_length=20, verbose_name='لون النص'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
