# Generated by Django 5.2.17 on 2026-10-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_tank_fuel_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='للسلايدر الرئيسي: 1920 × 600 بكسل. الشريط العلوي نصي ولا يحتاج صورة.', null=True, upload_to='banners/', verbose_name='صورة البنر (سطح المكتب)'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='للسلايدر على الهاتف: 1080 × 720 بكسل. الشريط العلوي نصي ولا يحتاج صورة.', null=True, upload_to='banners/mobile/', verbose_name='صورة البنر للهواتف'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('ticker', '📢 شريط متحرك علوي نصي (10%) - كل الصفحات العامة'), ('slider', '🎠 سلايدر رئيسي (30%) - الصفحة الرئيسية'), ('gateway_grid', '💎 إعلان بين بطاقات الرئيسية'), ('gateway_card', '🏷️ رعاية داخل بطاقات الرئيسية'), ('dealer_card', '🏪 رعاية داخل بطاقة كل وكيل')], default='ticker', max_length=20, verbose_name='الموقع'),
        ),
    ]
