# Generated by Django 6.1 on 2026-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_adbanner_image_url_adbanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='background_color',
            field=models.CharField(default='from-blue-700 via-indigo-700 to-purple-700', help_text='يستخدم هذا اللون إذا لم ترفع صورة', max_length=50, verbose_name='لون الخلفية'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('slider', 'شريط متحرك (أعلى الصفحة)'), ('hero', 'بنر رئيسي (أعلى الصفحة)'), ('footer', 'بنر سفلي (بين البطاقات والتذييل)')], default='footer', max_length=20, verbose_name='الموقع'),
        ),
    ]
