# Generated by Django 5.2.17 on 2026-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_adbanner_image_alter_adbanner_image_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='للسلايدر الرئيسي 30%: 1920 × 360 بكسل. الشريط العلوي نصي ولا يحتاج صورة.', null=True, upload_to='banners/', verbose_name='صورة البنر (سطح المكتب)'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='للسلايدر على الهاتف 30%: 1080 × 480 بكسل. الشريط العلوي نصي ولا يحتاج صورة.', null=True, upload_to='banners/mobile/', verbose_name='صورة البنر للهواتف'),
        ),
    ]
