# Generated by Django 6.1 on 2026-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_adbanner_subtitle_alter_adbanner_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecification',
            name='tire_psi',
        ),
        migrations.AddField(
            model_name='carspecification',
            name='tire_size',
            field=models.CharField(default='غير محدد', help_text='مثال: 215/60R16', max_length=50, verbose_name='حجم الإطار'),
        ),
    ]
