# Generated by Django 6.1 on 2026-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_carspecification_tire_psi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('ticker', '📢 شريط متحرك علوي (5%) - أعلى الصفحة'), ('slider', '🎠 سلايدر رئيسي (35%) - وسط الصفحة')], default='ticker', max_length=20, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='oil_brands',
            field=models.CharField(blank=True, help_text='مثال: Mobil 1, Castrol, Total', max_length=255, null=True, verbose_name='ماركات الزيت'),
        ),
    ]
