# Generated by Django 5.2.17 on 2026-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_adbanner_image_alter_adbanner_image_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='button_url',
            field=models.URLField(blank=True, help_text='اختياري. اتركه فارغاً إذا كان الإعلان نصياً فقط. مثال: /offers/ أو https://example.com', verbose_name='رابط الزر'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('ticker', '📢 شريط علوي ثابت/متبدل نصي - كل الصفحات العامة'), ('slider', '🎠 سلايدر رئيسي (30%) - الصفحة الرئيسية'), ('gateway_grid', '💎 إعلان بين بطاقات الرئيسية'), ('gateway_card', '🏷️ رعاية داخل بطاقات الرئيسية'), ('dealer_card', '🏪 رعاية داخل بطاقة كل وكيل')], default='ticker', max_length=20, verbose_name='الموقع'),
        ),
    ]
