# Generated by Django 6.1 on 2026-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_adbanner_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='📐 الأبعاد الموصى بها: 1400 × 500 بكسل (نسبة 2.8:1)', null=True, upload_to='banners/', verbose_name='صورة البنر'),
        ),
    ]
