# Generated by Django 5.2.17 on 2026-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_adbanner_button_url_alter_adbanner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_telegram_url',
            field=models.URLField(blank=True, help_text='مثال: https://t.me/username', verbose_name='رابط تلكرام للتواصل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_whatsapp_url',
            field=models.URLField(blank=True, help_text='مثال: https://wa.me/9647700000000', verbose_name='رابط واتساب للتواصل'),
        ),
    ]
