# Generated by Django 6.1 on 2026-08-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_adbanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecification',
            name='spec_region',
            field=models.CharField(choices=[('gcc', 'خليجي'), ('american', 'أمريكي'), ('european', 'أوروبي'), ('japanese', 'ياباني'), ('chinese', 'صيني'), ('other', 'أخرى')], default='gcc', max_length=20, verbose_name='مواصفات المنطقة'),
        ),
    ]
