# Generated by Django 5.2.17 on 2026-08-23 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carspecification_spec_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='📱 الأبعاد الموصى بها: 800 × 800 بكسل (نسبة 1:1)', null=True, upload_to='banners/mobile/', verbose_name='صورة البنر للهواتف'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='📐 الأبعاد الموصى بها: 1400 × 500 بكسل (نسبة 2.8:1)', null=True, upload_to='banners/', verbose_name='صورة البنر (سطح المكتب)'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='octane',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(80, message='رقم الأوكتان يجب أن يكون 80 أو أكثر'), django.core.validators.MaxValueValidator(120, message='رقم الأوكتان يجب أن يكون 120 أو أقل')]),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='السنة يجب أن تكون 1900 أو أكثر'), django.core.validators.MaxValueValidator(2099, message='السنة يجب أن تكون 2099 أو أقل')]),
        ),
        migrations.AddIndex(
            model_name='carspecification',
            index=models.Index(fields=['brand_ar'], name='cars_carspe_brand_a_cd2afa_idx'),
        ),
        migrations.AddIndex(
            model_name='carspecification',
            index=models.Index(fields=['model_ar'], name='cars_carspe_model_a_db4340_idx'),
        ),
        migrations.AddIndex(
            model_name='carspecification',
            index=models.Index(fields=['year'], name='cars_carspe_year_2e1946_idx'),
        ),
        migrations.AddIndex(
            model_name='carspecification',
            index=models.Index(fields=['engine_type'], name='cars_carspe_engine__103286_idx'),
        ),
        migrations.AddIndex(
            model_name='carspecification',
            index=models.Index(fields=['spec_region'], name='cars_carspe_spec_re_5e31f6_idx'),
        ),
    ]
