# Generated by Django 5.2.17 on 2026-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_adbanner_image_mobile_alter_adbanner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, help_text='إيموجي مثل 🚗 🔧 🧮 ⭐ — اتركه فارغاً إذا استخدمت صورة إعلان', max_length=16, verbose_name='الأيقونة')),
                ('image', models.ImageField(blank=True, help_text='إن وُجدت تُعرض بدل الأيقونة — مثالي لإعلانات الرعاة', null=True, upload_to='feature_ads/%Y/%m/', verbose_name='صورة إعلان')),
                ('link', models.URLField(blank=True, help_text='عند تعبئته تصبح البطاقة قابلة للنقر (إعلان)', verbose_name='رابط البطاقة')),
                ('order', models.IntegerField(default=0, help_text='0 = تظهر أولاً', verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, help_text='✔️ ظاهرة في الموقع | ❌ مخفية', verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'بطاقة مميزات',
                'verbose_name_plural': 'بطاقات المميزات',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
