# Generated by Django 5.2.17 on 2026-08-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_featurecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_ads', models.BooleanField(default=False, help_text='شغّلها بعد قبول موقعك في Google AdSense', verbose_name='تفعيل الإعلانات')),
                ('adsense_client_id', models.CharField(blank=True, help_text='مثال: ca-pub-1234567890123456', max_length=50, verbose_name='معرف الناشر AdSense')),
                ('ad_slot_results', models.CharField(blank=True, help_text='data-ad-slot من لوحة AdSense', max_length=20, verbose_name='رقم الوحدة: نتائج البحث')),
                ('ad_slot_recommend_top', models.CharField(blank=True, help_text='data-ad-slot من لوحة AdSense', max_length=20, verbose_name='رقم الوحدة: أعلى صفحة التوصيات')),
                ('ad_slot_recommend_bottom', models.CharField(blank=True, help_text='data-ad-slot من لوحة AdSense', max_length=20, verbose_name='رقم الوحدة: أسفل صفحة التوصيات')),
                ('ads_txt', models.TextField(blank=True, help_text='يُعرض على /ads.txt — الصق السطر الذي يعطيك إياه AdSense مثال: google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0', verbose_name='محتوى ads.txt')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
