# Generated by Django 5.2.17 on 2026-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='trim',
            field=models.CharField(blank=True, help_text='مثال: GLX، EX، سمارت، فل كامل', max_length=100, null=True, verbose_name='الفئة (Trim)'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='📐 الأبعاد الموصى بها: 1920 × 820 بكسل (نسبة 21:9) — الصورة تُقص تلقائياً', null=True, upload_to='banners/', verbose_name='صورة البنر (سطح المكتب)'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='📱 الأبعاد الموصى بها: 800 × 600 بكسل (نسبة 4:3)', null=True, upload_to='banners/mobile/', verbose_name='صورة البنر للهواتف'),
        ),
    ]
