# Generated by Django 5.2.17 on 2026-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_carspecification_trim_alter_adbanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='battery',
            field=models.CharField(blank=True, help_text='مثال: 55D23L، 60Ah، 12V 70Ah', max_length=100, null=True, verbose_name='البطارية (الحجم/السعة)'),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='transmission_oil_brands',
            field=models.CharField(blank=True, help_text='مثال: Toyota Genuine ATF, Idemitsu, AISIN', max_length=255, null=True, verbose_name='ماركات زيت الناقل'),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='transmission_oil_spec',
            field=models.CharField(blank=True, help_text='مثال: ATF WS، ATF SP-III، Dexron VI', max_length=100, null=True, verbose_name='مواصفات زيت الناقل'),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='transmission_type',
            field=models.CharField(blank=True, help_text='مثال: أوتوماتيك 6 سرعات، CVT، Manual', max_length=50, null=True, verbose_name='نوع ناقل الحركة'),
        ),
    ]
