# Generated by Django 5.2.17 on 2026-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_carspecification_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='brand_norm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='engine_norm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='model_norm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
