# Generated by Django 5.2.17 on 2026-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_sitesettings_ga_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='مفتاح API من platform.deepseek.com — للميزات الذكية (شكد فلوسك، مقارنة، أسعار)', max_length=100, verbose_name='مفتاح DeepSeek API'),
        ),
    ]
