# Generated by Django 5.2.17 on 2026-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_sitesettings_deepseek_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='من aistudio.google.com — احتياطي تلقائي إذا تعطل Groq', max_length=200, verbose_name='مفتاح Gemini (الاحتياطي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='من console.groq.com — الأساسي لميزة شكد فلوسك (مجاني بدون بطاقة)', max_length=200, verbose_name='مفتاح Groq (الأساسي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='مفتاح API من platform.deepseek.com — احتياطي اختياري', max_length=100, verbose_name='مفتاح DeepSeek API'),
        ),
    ]
