# Generated by Django 5.2.17 on 2026-09-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_sitesettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشركة')),
                ('slug', models.SlugField(help_text='يُستخدم في رابط صفحة التحقق — مثال: hisam → sayarti.org/verify/hisam/', max_length=100, unique=True, verbose_name='المعرّف (slug)')),
                ('code_prefix', models.CharField(help_text='بداية الكود المولّد — مثال: HISAM → كود مثل HISAM-4821', max_length=20, verbose_name='بادئة الكود')),
                ('discount', models.IntegerField(default=10, help_text='تُعرض للزائر عند توليد الكود وتظهر لموظف الشركة في الفحص', verbose_name='نسبة الخصم %')),
                ('website', models.URLField(blank=True, help_text='اختياري — يُعرض كرابط للزائر للمزيد حول الشركة', verbose_name='الموقع / صفحة الشركة')),
                ('is_active', models.BooleanField(default=True, help_text='✔️ نشطة والأكواد تُولَّد منها | ❌ متوقفة', verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'شركة راعية',
                'verbose_name_plural': 'الشركات الراعية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='يُولَّد تلقائياً — مثال HISAM-4821', max_length=40, unique=True, verbose_name='الكود')),
                ('status', models.CharField(choices=[('active', 'ساري (غير مستخدم)'), ('used', 'مُستخدم')], default='active', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='cars.sponsor', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'كود خصم',
                'verbose_name_plural': 'أكواد الخصم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adbanner',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='اربط البنر بشركة راعية ليظهر فيها زر «احصل على خصم»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='cars.sponsor', verbose_name='الشركة الراعية'),
        ),
    ]
