# Generated by Django 5.2.17 on 2026-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_sponsor_promocode_adbanner_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='password',
            field=models.CharField(blank=True, help_text='يستخدمها الراعي لتسجيل الدخول إلى «نافذة الخدمات» للتحقق من الأكواد — تُخزَّن مشفّرة', max_length=128, verbose_name='كلمة مرور حساب الراعي'),
        ),
    ]
