# Generated by Django 5.2.17 on 2026-09-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_sponsor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='اربط البطاقة بشركة راعية ليظهر فيها زر «احصل على خصم»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_cards', to='cars.sponsor', verbose_name='الشركة الراعية'),
        ),
    ]
