# Generated by Django 5.2.17 on 2026-09-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_featurecard_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='verified_by',
            field=models.CharField(blank=True, default='', help_text='اسم الشركة التي فحصت واستخدمت الكود', max_length=150, verbose_name='تم التحقق من قبل'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='cars.sponsor', verbose_name='الشركة المولّدة'),
        ),
    ]
