# Generated by Django 5.2.17 on 2026-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_promocode_verified_by_alter_promocode_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التوليد'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('active', 'ساري (غير مستخدم)'), ('used', 'مُستخدم')], db_index=True, default='active', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستخدام'),
        ),
    ]
