# Generated by Django 5.2.17 on 2026-09-07 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_alter_promocode_created_at_alter_promocode_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='اسم السيارة الكامل')),
                ('brand', models.CharField(max_length=100, verbose_name='الماركة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('brand_norm', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('model_norm', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2099)], verbose_name='السنة')),
                ('car_type', models.CharField(choices=[('all', 'عام'), ('japanese', 'ياباني'), ('korean', 'كوري'), ('chinese', 'صيني'), ('american', 'أمريكي'), ('german', 'ألماني'), ('european', 'أوروبي'), ('iranian', 'إيراني')], db_index=True, default='all', max_length=20, verbose_name='نوع السيارة')),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], db_index=True, default='used', max_length=10, verbose_name='الحالة')),
                ('price_min_iqd', models.PositiveBigIntegerField(verbose_name='أقل سعر بالدينار')),
                ('price_max_iqd', models.PositiveBigIntegerField(verbose_name='أعلى سعر بالدينار')),
                ('price_min_usd', models.PositiveIntegerField(blank=True, null=True, verbose_name='أقل سعر بالدولار')),
                ('price_max_usd', models.PositiveIntegerField(blank=True, null=True, verbose_name='أعلى سعر بالدولار')),
                ('engine', models.CharField(blank=True, max_length=80, verbose_name='المحرك')),
                ('fuel_economy', models.CharField(blank=True, default='جيد', max_length=50, verbose_name='صرف الوقود')),
                ('maintenance', models.CharField(blank=True, default='متوسطة', max_length=50, verbose_name='الصيانة')),
                ('pros', models.CharField(blank=True, max_length=240, verbose_name='سبب الترشيح')),
                ('confidence', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درجة الثقة')),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('import', 'استيراد ملف')], db_index=True, default='manual', max_length=20, verbose_name='المصدر')),
                ('source_note', models.CharField(blank=True, max_length=220, verbose_name='ملاحظة المصدر')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعل')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'سعر سيارة في السوق',
                'verbose_name_plural': 'أسعار السيارات في السوق',
                'ordering': ['price_min_iqd', '-confidence', 'brand', 'model'],
                'indexes': [models.Index(fields=['condition', 'car_type', 'price_min_iqd'], name='cars_market_conditi_80ce03_idx'), models.Index(fields=['condition', 'car_type', 'price_min_usd'], name='cars_market_conditi_6af30d_idx'), models.Index(fields=['brand_norm', 'model_norm'], name='cars_market_brand_n_cec00c_idx')],
            },
        ),
    ]
