# Generated by Django 5.2.17 on 2026-09-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_marketcarprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketcarprice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketcarprice',
            name='source',
        ),
        migrations.RemoveField(
            model_name='marketcarprice',
            name='source_note',
        ),
    ]
