# Generated by Django 5.2.17 on 2026-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_remove_marketcarprice_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcarprice',
            name='brand_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الماركة إنجليزي'),
        ),
        migrations.AddField(
            model_name='marketcarprice',
            name='model_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الموديل إنجليزي'),
        ),
        migrations.AlterField(
            model_name='marketcarprice',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='الماركة عربي'),
        ),
        migrations.AlterField(
            model_name='marketcarprice',
            name='model',
            field=models.CharField(max_length=100, verbose_name='الموديل عربي'),
        ),
    ]
