# Generated by Django 5.2.17 on 2026-09-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_reset_market_prices_for_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcarprice',
            name='id1',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID خارجي'),
        ),
    ]
