# Generated by Django 5.2.17 on 2026-09-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_marketcarprice_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='مفتاح API من platform.deepseek.com — المزود الأساسي لميزة شكد فلوسك', max_length=100, verbose_name='مفتاح DeepSeek API (الأساسي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='من aistudio.google.com — احتياطي إذا تعطل DeepSeek', max_length=200, verbose_name='مفتاح Gemini (احتياطي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='من console.groq.com — يستخدم للميزات العامة فقط ولا يعتمد عليه شكد فلوسك', max_length=200, verbose_name='مفتاح Groq'),
        ),
    ]
