# Generated by Django 5.2.17 on 2026-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_alter_sitesettings_deepseek_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='من console.groq.com — يستخدم في شكد فلوسك فقط إذا فشل DeepSeek وGemini', max_length=200, verbose_name='مفتاح Groq (حائط صد أخير)'),
        ),
    ]
