# Generated by Django 5.2.17 on 2026-09-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0039_update_ai_help_texts_db_only_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_dealers_card',
            field=models.BooleanField(default=True, help_text='فعّلها لإظهار بطاقة الوكلاء في واجهة الموقع، وألغها لإخفائها.', verbose_name='إظهار بطاقة وكلاء الزيوت وقطع الغيار'),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_type', models.CharField(choices=[('oil', 'وكلاء الزيوت'), ('parts', 'وكلاء قطع الغيار')], db_index=True, max_length=12, verbose_name='نوع الوكيل')),
                ('parts_region', models.CharField(choices=[('all', 'عام'), ('japanese', 'ياباني'), ('chinese', 'صيني'), ('iranian', 'إيراني'), ('american', 'أمريكي'), ('german', 'ألماني')], db_index=True, default='all', max_length=20, verbose_name='تصنيف قطع الغيار')),
                ('name', models.CharField(max_length=160, verbose_name='اسم الوكيل')),
                ('governorate', models.CharField(blank=True, max_length=80, verbose_name='المحافظة')),
                ('address', models.CharField(blank=True, max_length=220, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='رقم واتساب')),
                ('website', models.URLField(blank=True, verbose_name='رابط الموقع / الصفحة')),
                ('brands', models.CharField(blank=True, max_length=220, verbose_name='الماركات / الاختصاص')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل الوكيل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ظاهر في الموقع')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='وكيل مميز')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'وكيل زيوت أو قطع غيار',
                'verbose_name_plural': 'وكلاء الزيوت وقطع الغيار',
                'ordering': ['dealer_type', 'parts_region', '-is_featured', 'order', 'name'],
                'indexes': [models.Index(fields=['dealer_type', 'parts_region', 'is_active'], name='cars_dealer_dealer__f395f0_idx')],
            },
        ),
    ]
