# Generated by Django 5.2.17 on 2026-09-11 18:20

import django.db.models.deletion
from django.db import migrations, models


def hide_dealers_card(apps, schema_editor):
    SiteSettings = apps.get_model('cars', 'SiteSettings')
    SiteSettings.objects.update(show_dealers_card=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0040_sitesettings_show_dealers_card_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('prompt_click', 'ضغط زر التثبيت'), ('installed', 'تثبيت فعلي')], max_length=20, unique=True, verbose_name='نوع الحدث')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='العدد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عداد تثبيت التطبيق',
                'verbose_name_plural': 'عدادات تثبيت التطبيق',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='DealerClickMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('phone', 'اتصال'), ('whatsapp', 'واتساب'), ('website', 'الموقع')], max_length=20, verbose_name='نوع النقرة')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='العدد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_metrics', to='cars.dealer', verbose_name='الوكيل')),
            ],
            options={
                'verbose_name': 'عداد تواصل وكيل',
                'verbose_name_plural': 'عدادات تواصل الوكلاء',
                'ordering': ['dealer__name', 'action'],
                'unique_together': {('dealer', 'action')},
            },
        ),
        migrations.DeleteModel(
            name='MarketCarPrice',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='مفتاح API من platform.deepseek.com — يستخدم في ميزات البحث الذكي فقط', max_length=100, verbose_name='مفتاح DeepSeek API (الأساسي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='exchange_rate_iqd_per_usd',
            field=models.PositiveIntegerField(default=1500, help_text='سعر السوق الموازي: كم دينار عراقي لكل 1 دولار.', verbose_name='سعر صرف الدولار مقابل الدينار'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='من aistudio.google.com — يستخدم في ميزات البحث الذكي فقط', max_length=200, verbose_name='مفتاح Gemini (احتياطي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='من console.groq.com — يستخدم في ميزات البحث الذكي فقط', max_length=200, verbose_name='مفتاح Groq (حائط صد أخير)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_dealers_card',
            field=models.BooleanField(default=False, help_text='فعّلها لإظهار بطاقة الوكلاء في واجهة الموقع، وألغها لإخفائها.', verbose_name='إظهار بطاقة وكلاء الزيوت وقطع الغيار'),
        ),
        migrations.RunPython(hide_dealers_card, migrations.RunPython.noop),
    ]
