# Generated by Django 5.2.17 on 2026-09-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0041_appinstallmetric_dealerclickmetric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecification',
            name='spark',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='exchange_rate_iqd_per_usd',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='exchange_rate_source',
        ),
    ]
