# Generated by Django 5.2.17 on 2026-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0042_remove_carspecification_spark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='engine_code',
            field=models.CharField(blank=True, help_text='مثال: 2ZR-FE، G4NA، M274', max_length=100, null=True, verbose_name='كود المحرك'),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='spark',
            field=models.CharField(blank=True, help_text='مثال: NGK Iridium', max_length=100, null=True, verbose_name='شمعات الاحتراق'),
        ),
    ]
