# Generated by Django 5.2.17 on 2026-09-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_carspecification_engine_code_carspecification_spark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='اسم العرض')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='رابط SEO')),
                ('category', models.CharField(choices=[('engine', 'المحرك'), ('cooling', 'التبريد'), ('fuel', 'الوقود'), ('electrical', 'الكهرباء'), ('transmission', 'ناقل الحركة'), ('suspension', 'التعليق'), ('brakes', 'الفرامل'), ('tires', 'الإطارات'), ('other', 'أخرى')], default='engine', max_length=30, verbose_name='التصنيف')),
                ('description', models.TextField(verbose_name='وصف العرض')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='درجة الخطورة')),
                ('safety_status', models.CharField(choices=[('drive_carefully', 'يمكن القيادة بحذر'), ('check_soon', 'افحص قريباً'), ('stop_now', 'أوقف السيارة'), ('tow_required', 'يفضل سطحة')], default='check_soon', max_length=30, verbose_name='مؤشر الأمان')),
                ('driver_questions', models.TextField(blank=True, verbose_name='أسئلة للسائق')),
                ('self_check_steps', models.TextField(blank=True, verbose_name='خطوات فحص ذاتي')),
                ('urgent_warning', models.TextField(blank=True, verbose_name='تحذير عاجل')),
                ('seo_title', models.CharField(blank=True, max_length=220, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='وصف SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عرض عطل',
                'verbose_name_plural': 'أعراض الأعطال',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['slug'], name='cars_carsym_slug_bc93c7_idx'), models.Index(fields=['category'], name='cars_carsym_categor_2ce55e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='اسم المهمة')),
                ('category', models.CharField(choices=[('oil', 'زيوت'), ('filters', 'فلاتر'), ('spark', 'شمعات القدح'), ('cooling', 'تبريد'), ('transmission', 'ناقل الحركة'), ('brakes', 'فرامل'), ('electrical', 'كهرباء'), ('tires', 'إطارات'), ('inspection', 'فحص عام')], default='inspection', max_length=30, verbose_name='التصنيف')),
                ('interval_km', models.PositiveIntegerField(default=10000, verbose_name='كل كم كيلومتر')),
                ('interval_months', models.PositiveSmallIntegerField(default=12, verbose_name='كل كم شهر')),
                ('severe_interval_km', models.PositiveIntegerField(default=5000, verbose_name='كل كم في الظروف الشاقة')),
                ('severe_interval_months', models.PositiveSmallIntegerField(default=6, verbose_name='كل كم شهر في الظروف الشاقة')),
                ('start_km', models.PositiveIntegerField(default=0, verbose_name='تبدأ من ممشى')),
                ('importance', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأهمية')),
                ('description', models.TextField(blank=True, verbose_name='شرح المهمة')),
                ('iraq_note', models.TextField(blank=True, verbose_name='ملاحظة للظروف العراقية')),
                ('applies_to_engine_type', models.CharField(choices=[('all', 'الكل'), ('regular', 'بنزين عادي'), ('hybrid', 'هايبرد'), ('turbo', 'تيربو'), ('diesel', 'ديزل'), ('electric', 'كهربائي')], default='all', max_length=20, verbose_name='نوع المحرك')),
                ('applies_to_transmission', models.CharField(choices=[('all', 'الكل'), ('automatic', 'أوتوماتيك'), ('cvt', 'CVT'), ('manual', 'عادي')], default='all', max_length=20, verbose_name='نوع ناقل الحركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
            ],
            options={
                'verbose_name': 'مهمة صيانة',
                'verbose_name_plural': 'مهام الصيانة',
                'ordering': ['start_km', 'severe_interval_km', 'name'],
                'indexes': [models.Index(fields=['category'], name='cars_mainte_categor_c290c3_idx'), models.Index(fields=['start_km'], name='cars_mainte_start_k_362e53_idx'), models.Index(fields=['severe_interval_km'], name='cars_mainte_severe__d8ab6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OBDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='كود العطل')),
                ('title', models.CharField(max_length=180, verbose_name='العنوان')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='رابط SEO')),
                ('system', models.CharField(choices=[('engine', 'المحرك'), ('transmission', 'ناقل الحركة'), ('emissions', 'الانبعاثات'), ('electrical', 'الكهرباء'), ('fuel', 'الوقود'), ('cooling', 'التبريد'), ('other', 'أخرى')], default='engine', max_length=30, verbose_name='النظام')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='درجة الخطورة')),
                ('safety_status', models.CharField(choices=[('drive_carefully', 'يمكن القيادة بحذر'), ('check_soon', 'افحص قريباً'), ('stop_now', 'أوقف السيارة'), ('tow_required', 'يفضل سطحة')], default='check_soon', max_length=30, verbose_name='مؤشر الأمان')),
                ('plain_explanation', models.TextField(verbose_name='شرح مبسط')),
                ('local_explanation', models.TextField(blank=True, verbose_name='شرح باللهجة المحلية')),
                ('common_causes', models.TextField(blank=True, verbose_name='الأسباب الشائعة')),
                ('local_causes', models.TextField(blank=True, verbose_name='أسباب شائعة محلياً')),
                ('symptoms', models.TextField(blank=True, verbose_name='الأعراض المتوقعة')),
                ('self_check_steps', models.TextField(blank=True, verbose_name='خطوات فحص ذاتي')),
                ('mechanic_advice', models.TextField(blank=True, verbose_name='نصيحة مراجعة المختص')),
                ('dont_do', models.TextField(blank=True, verbose_name='أشياء لا تفعلها')),
                ('estimated_cost_note', models.TextField(blank=True, verbose_name='ملاحظة التكلفة')),
                ('seo_title', models.CharField(blank=True, max_length=220, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='وصف SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'كود عطل OBD',
                'verbose_name_plural': 'أكواد الأعطال OBD',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='cars_obdcod_code_3ee0a8_idx'), models.Index(fields=['slug'], name='cars_obdcod_slug_902972_idx'), models.Index(fields=['system'], name='cars_obdcod_system_f3f1de_idx')],
            },
        ),
        migrations.CreateModel(
            name='SymptomCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='السبب المحتمل')),
                ('description', models.TextField(blank=True, verbose_name='شرح السبب')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('likelihood', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='الاحتمالية')),
                ('check_method', models.TextField(blank=True, verbose_name='طريقة الفحص')),
                ('solution_hint', models.TextField(blank=True, verbose_name='إشارة للحل')),
                ('related_obd_codes', models.CharField(blank=True, max_length=120, verbose_name='أكواد مرتبطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='cars.carsymptom', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'سبب عرض',
                'verbose_name_plural': 'أسباب الأعراض',
                'ordering': ['symptom', 'priority', 'id'],
            },
        ),
    ]
