# Generated by Django 5.2.17 on 2026-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0045_seed_maintenance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_maintenance_card',
            field=models.BooleanField(default=False, help_text='فعّلها لإظهار بطاقة الصيانة والأعطال في واجهة الموقع، وألغها لإخفائها أثناء تجهيز البيانات.', verbose_name='إظهار بطاقة الصيانة والأعطال'),
        ),
    ]
