# Generated by Django 5.2.17 on 2026-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0046_sitesettings_show_maintenance_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['brand_ar', 'brand_en', 'start_km', 'severe_interval_km', 'name'], 'verbose_name': 'مهمة صيانة', 'verbose_name_plural': 'مهام الصيانة'},
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='brand_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشركة بالعربي'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='brand_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشركة بالإنكليزي'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='manufacturer_note',
            field=models.TextField(blank=True, verbose_name='توصية الشركة الأم'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['brand_ar'], name='cars_mainte_brand_a_96cec3_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['brand_en'], name='cars_mainte_brand_e_90ccfc_idx'),
        ),
    ]
