# Generated by Django 5.2.17 on 2026-09-17 15:11

from django.db import migrations, models


def normalize_engine_types(apps, schema_editor):
    MaintenanceTask = apps.get_model('cars', 'MaintenanceTask')
    MaintenanceTask.objects.filter(applies_to_engine_type='regular').update(applies_to_engine_type='gasoline')
    MaintenanceTask.objects.filter(applies_to_engine_type='turbo').update(applies_to_engine_type='gasoline_turbo')


def reverse_engine_types(apps, schema_editor):
    MaintenanceTask = apps.get_model('cars', 'MaintenanceTask')
    MaintenanceTask.objects.filter(applies_to_engine_type='gasoline').update(applies_to_engine_type='regular')
    MaintenanceTask.objects.filter(applies_to_engine_type='gasoline_turbo').update(applies_to_engine_type='turbo')


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0047_alter_maintenancetask_options_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_engine_types, reverse_engine_types),
        migrations.AlterField(
            model_name='maintenancetask',
            name='applies_to_engine_type',
            field=models.CharField(choices=[('all', 'الكل'), ('gasoline', 'بنزين بدون تيربو'), ('gasoline_turbo', 'بنزين تيربو'), ('hybrid', 'هايبرد'), ('diesel', 'ديزل'), ('electric', 'كهربائي')], default='all', max_length=20, verbose_name='نوع المحرك'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='applies_to_transmission',
            field=models.CharField(choices=[('all', 'الكل'), ('automatic', 'أوتوماتيك'), ('cvt', 'CVT'), ('ecvt', 'e-CVT'), ('dct', 'DCT'), ('amt', 'AMT'), ('manual', 'عادي')], default='all', max_length=20, verbose_name='نوع ناقل الحركة'),
        ),
    ]
