# Generated by Django 5.2.17 on 2026-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0048_alter_maintenancetask_applies_to_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('ticker', '📢 شريط متحرك علوي (5%) - أعلى الصفحة'), ('slider', '🎠 سلايدر رئيسي (35%) - وسط الصفحة'), ('gateway_grid', '💎 إعلان بين بطاقات الرئيسية'), ('gateway_card', '🏷️ رعاية صغيرة داخل بطاقات الرئيسية')], default='ticker', max_length=20, verbose_name='الموقع'),
        ),
        migrations.DeleteModel(
            name='FeatureCard',
        ),
    ]
