# Generated by Django 5.2.17 on 2026-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0049_alter_adbanner_position_delete_featurecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='position',
            field=models.CharField(choices=[('ticker', '📢 شريط متحرك علوي (5%) - أعلى الصفحة'), ('slider', '🎠 سلايدر رئيسي (35%) - وسط الصفحة'), ('gateway_grid', '💎 إعلان بين بطاقات الرئيسية'), ('gateway_card', '🏷️ رعاية داخل بطاقات الرئيسية'), ('dealer_card', '🏪 رعاية داخل بطاقة كل وكيل')], default='ticker', max_length=20, verbose_name='الموقع'),
        ),
    ]
