# Generated by Django 5.2.17 on 2026-09-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0050_add_dealer_card_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OBDCode',
        ),
        migrations.RemoveField(
            model_name='symptomcause',
            name='related_obd_codes',
        ),
    ]
